### ISSUE TITLE
[Bug Report] Callout no establece valor en frontend

### ISSUE THREAD

**Issue by rcapecce** [solop-develop/vue-1.0#1904]
## Bug report

El callout que establece la dirección del SDN al elegir el SDN no está pudiendo establecerse en el frontend, si es obtenido el C_BPartner_Location_ID pero no lo está estableciendo en el campo

#### Steps to reproduce

1. Abrir ventana Orden de Trabajo
2. Crear nuevo registro
3. Completar SDN "Cliente Ejemplo"
4. Observar la respuesta en Red como obtiene el id de C_BPartner_Location_ID pero no lo establece en el campo

#### Screenshot or Gif（截图或动态图）

![Peek 2024-02-12 14-12](https://github.com/solop-develop/frontend-core/assets/14218144/6e64dd94-c188-4a06-9753-328dd7c98546)

**Comment by EdwinBetanc0urt** [comment]
No puedo replicar este error

```log
===========> GridTab.processCallout: class [268]
java.lang.ClassNotFoundException: org.openup.core.callout.CalloutOpUpOrder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at org.compiere.model.GridTab.processCallout(GridTab.java:2701)
        at org.compiere.model.GridTab.lambda$dataNew$1(GridTab.java:1175)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.compiere.model.GridTab.dataNew(GridTab.java:1175)
        at org.spin.grpc.service.UserInterface.lambda$22(UserInterface.java:2629)
        at org.compiere.util.Trx.run(Trx.java:529)
        at org.compiere.util.Trx.run(Trx.java:497)
        at org.spin.grpc.service.UserInterface.runcallout(UserInterface.java:2563)
        at org.spin.grpc.service.UserInterface.runCallout(UserInterface.java:2536)
        at org.spin.backend.grpc.user_interface.UserInterfaceGrpc$MethodHandlers.invoke(UserInterfaceGrpc.java:2208)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
```

No consigue la clase del callout `org.openup.core.callout.CalloutOpUpOrder`.

**Comment by EdwinBetanc0urt** [comment]
Esto no se puede replicar localmente al no tener los fuentes de los callouts de esa ventana.
