### ISSUE TITLE
Error 500 random al correr callout desde proyecto

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2156]
## Bug report
En la ventana Proyectos tneemos definido un Callout que a partrir del Campo "SDN" define dirección, lista de preciio y región de ventas en el proyuecto. Ahora esto funciona normalmente bien pero en ciertas ocaciones por algún motivo que desconozco salta un error 500 y no carga bien los datos. si se vuelve a intentar se ve que aleatoriamente hay veces que aparece y hay veces que no.

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/0cbeff2a-55a6-4264-af9d-2c4946aebfec

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  3.7.2

**Comment by rcapecce** [comment]
```
curl 'http://cac-test.solopcloud.com/api/user-interface/run-callout/2000194/C_BPartner_ID/org.openup.core.callout.CalloutOpUpOrder.setBPLocationSrvOrder,org.openup.core.callout.CalloutOpUpOrder.setPriceListVerSrvOrder,org.openup.core.callout.CalloutOpUpOrder.setPaymentTermSrvOrder,org.openup.core.callout.CalloutOpUpOrder.setFromBPartnerProject' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: es-419,es;q=0.9' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIyMDE4MzQ3IiwiQURfQ2xpZW50X0lEIjoxMDAwMDAxLCJBRF9PcmdfSUQiOjEwMDAwMDQsIkFEX1JvbGVfSUQiOjEwMDAwMzIsIkFEX1VzZXJfSUQiOjEwMDAwMTIsIk1fV2FyZWhvdXNlX0lEIjoxMDAwMDcxLCJBRF9MYW5ndWFnZSI6ImVuX1VTIiwiaWF0IjoxNzEzNDQ2ODAwLCJleHAiOjE3MTM1MzMyMDB9.e7R55hAZgs1y6tzD6WRQJOHHsntIdUeTIZg2-cpfUyk' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: language=en' \
  -H 'Origin: http://cac-test.solopcloud.com' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://cac-test.solopcloud.com/' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' \
  --data-raw '{"tab_id":2000194,"context_attributes":{"IsCommitment":false,"InvoicedQty":{"type":"decimal","value":0},"IsSummary":false,"ProjectCategory":"N","IsCommitCeiling":false,"CommittedQty":{"type":"decimal","value":0},"ProjInvoiceRule":"-","InvoicedAmt":{"type":"decimal","value":0},"PlannedAmt":{"type":"decimal","value":0},"PlannedMarginAmt":{"type":"decimal","value":0},"PlannedQty":{"type":"decimal","value":0},"ProjectBalanceAmt":{"type":"decimal","value":0},"CommittedAmt":{"type":"decimal","value":0},"C_ProjectType_ID":"1000023","AD_Client_ID":1000001,"Processed":false,"IsApprovedAttachment":false,"IsCustomerApproved":false,"C_BPartner_ID":1003026,"IsActive":true,"ProjectManager_ID":1000012,"ProjectLineLevel":"P","C_ProjectClass_ID":1000001,"C_ProjectStatus_ID":1000011,"C_Currency_ID":100,"C_PaymentTerm_ID":1000000,"AD_Org_ID":1000004,"IsIndefinite":false,"isPred":false,"Created":"2024-02-02 12:00:00","CreatedBy":1000010,"Updated":"2024-02-14 05:33:13","UpdatedBy":1000004,"PercentFinishedWork":"0.00","CostAdjustment":false,"displaycolumn_c_period_id":"1000157","IsPrinted":true,"PlannedPrice":0,"MultiplyRate":1,"QtyEntered":1,"IsBonusProduct":false,"undefined":1003026},"column_name":"C_BPartner_ID","callout":"org.openup.core.callout.CalloutOpUpOrder.setBPLocationSrvOrder,org.openup.core.callout.CalloutOpUpOrder.setPriceListVerSrvOrder,org.openup.core.callout.CalloutOpUpOrder.setPaymentTermSrvOrder,org.openup.core.callout.CalloutOpUpOrder.setFromBPartnerProject","value":1003026}' \
  --compressed \
  --insecure
```

Respuesta

```
{
 "code": 13,
 "message": "",
 "details": []
}
```

Backend

```
===========> MLookupFactory.getLookup_TableDir: No Identifier records found: UY_BP_ProjectMember_ID [28601]                                                                                                                                
===========> MLookupFactory.getLookupInfo: No SQL - UY_BP_ProjectMember_ID [28601]                                                                                                                                                         
===========> MMeasure.getGraphColumnList: SELECT COUNT(*), COALESCE(s.Name,TO_NCHAR('-')), s.R_Status_ID, s.SeqNo FROM R_Request LEFT OUTER JOIN R_Status s ON (R_Request.R_Status_ID=s.R_Status_ID) WHERE R_Request.R_RequestType_ID=10000
00 AND R_Request.Processed<>'Y' AND R_Request.AD_Client_ID IN(0,1000001) AND R_Request.AD_Org_ID IN(0,1000004) AND (R_Request.R_Request_ID IS NULL OR R_Request.R_Request_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Tabl
e_ID = 417 AND AD_User_ID <> 1000012 AND IsActive = 'Y' )) AND (s.R_Status_ID IS NULL OR s.R_Status_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 776 AND AD_User_ID <> 1000012 AND IsActive = 'Y' )) GROUP BY CO
ALESCE(s.Name,TO_NCHAR('-')), s.R_Status_ID, s.SeqNo  ORDER BY s.SeqNo [28900]                                                                                                                                                             
org.postgresql.util.PSQLException: Bad value for type timestamp/date/time: -; State=22007; ErrorCode=0                                                                                                                                     
        at org.postgresql.jdbc.TimestampUtils.parseBackendTimestamp(TimestampUtils.java:363)                                                                                                                                               
        at org.postgresql.jdbc.TimestampUtils.toTimestamp(TimestampUtils.java:395)                                                                                                                                                         
        at org.postgresql.jdbc.PgResultSet.getTimestamp(PgResultSet.java:638)                                                                                                                                                              
        at org.postgresql.jdbc.PgResultSet.getTimestamp(PgResultSet.java:2734)                                                                                                                                                             
        at com.zaxxer.hikari.pool.HikariProxyResultSet.getTimestamp(HikariProxyResultSet.java)                                                                                                                                             
        at org.compiere.model.MMeasure.getGraphColumnList(MMeasure.java:222)                                                                                                                                                               
        at org.spin.grpc.service.Dashboarding.getMetrics(Dashboarding.java:178)                                                                                                                                                            
        at org.spin.grpc.service.Dashboarding.getMetrics(Dashboarding.java:116)                                                                                                                                                            
        at org.spin.backend.grpc.dashboarding.DashboardingGrpc$MethodHandlers.invoke(DashboardingGrpc.java:791)                                                                                                                            
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)                                                                                                                       
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)                                                                                                                            
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829) 
caused by: java.lang.NumberFormatException
        at org.postgresql.jdbc.TimestampUtils.number(TimestampUtils.java:1025)
        at org.postgresql.jdbc.TimestampUtils.parseBackendTimestamp(TimestampUtils.java:230)
        at org.postgresql.jdbc.TimestampUtils.toTimestamp(TimestampUtils.java:395)
        at org.postgresql.jdbc.PgResultSet.getTimestamp(PgResultSet.java:638)
        at org.postgresql.jdbc.PgResultSet.getTimestamp(PgResultSet.java:2734)
        at com.zaxxer.hikari.pool.HikariProxyResultSet.getTimestamp(HikariProxyResultSet.java)
        at org.compiere.model.MMeasure.getGraphColumnList(MMeasure.java:222)
        at org.spin.grpc.service.Dashboarding.getMetrics(Dashboarding.java:178)
        at org.spin.grpc.service.Dashboarding.getMetrics(Dashboarding.java:116)
        at org.spin.backend.grpc.dashboarding.DashboardingGrpc$MethodHandlers.invoke(DashboardingGrpc.java:791)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)


```

**Comment by mgarciaQ76** [comment]
Como comentario adicional a esta issue. El error al seleccionar SDN se da aleatoriamente si se selecciona de la lista desplegable y también si se selecciona desde la ventana emergente.

Este mensaje también se genera al seleccionar Producto en la línea de proyecto:

![image (1)](https://github.com/solop-develop/frontend-core/assets/139590879/ba0274d6-170a-40e5-8837-4475e2a60b52)

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/3.9.3


https://github.com/solop-develop/frontend-core/assets/78000356/f455575d-8c95-40cb-b8a4-d0b0f03ddbf2
