### ISSUE TITLE
Reporte Jasper desde VUE

### ISSUE THREAD

**Issue by niclopup** [solop-develop/vue-1.0#2435]
## Bug report

No se visualizan reportes Jasper desde VUE

**Comment by EdwinBetanc0urt** [comment]
Existe algún ejemplo en sp-custom? o con cual reporte podríamos hacer pruebas?

**Comment by EdwinBetanc0urt** [comment]
En el log se ven algunos mensajes 

```
2024-09-19T18:05:30.977255971Z ===========> ReportStarter.startProcess: No report file found for given type, falling back to attachment:inf_Product_Catalog_Order.jasper [19]
2024-09-19T18:05:31.146989680Z ===========> ReportStarter.startProcess: Can not find report file at path - attachment:inf_Product_Catalog_Order.jasper [19]
```

**Comment by yamelsenih** [comment]
Hola, bastaría con agregar un ejemplo para validar.

Sugiero:
- Opción del Menú
- Parámetros

**Comment by niclopup** [comment]
Agrego ejemplo de como debería visualizarse correctamente un Jasper

Instancia:  
VUE: http://spdev02.solopapp.com:24810/vue#/
ZK: http://spdev02.solopapp.com:24810/webui/index.zul
Rol: "Educación - Admin"
Organización: Colegio
Ventana: Cálculo de Morosidad
Pestaña: Entrada

Uploading Ejemplo Reporte Jasper no funciona en VUE.mp4…


https://github.com/user-attachments/assets/e9c12876-4ae1-49d1-9cff-47b21bb650ee

lo intenté lanzar desde ZK y veo que tampoco funciona... 

![image](https://github.com/user-attachments/assets/b0a3816f-2217-4b26-b5e5-82d45dbbc216)

https://github.com/user-attachments/assets/022285d7-c6de-40fc-a17b-43519c12f42b

**Comment by niclopup** [comment]
Otro ejemplo de Jasper desde DxC "Factura líneas CFE"


https://github.com/user-attachments/assets/2c66c15d-2fe6-4a3f-b27a-cd80f8be8618



[trace Jasper.log](https://github.com/user-attachments/files/17169058/trace.Jasper.log)

**Comment by yamelsenih** [comment]
Hola, el error que está dando tiene que ver con la configuración de adjuntos del lado de **System**, esto debería tener el uso nativo de adjuntos

**Comment by rcapecce** [comment]
Se requiere implementar servicio para hostear internamente los reportes Jaspers.

Actualmente estos reportes estaban hosteados en la db en el proceso con `attachment:`.
Eso con S3  actualmente no tiene soporte así que los reportes no se están generando.
@yamelsenih comenta que una posible solución es tener un servicio de hosting interno donde se puedan referenciar estos jasper desde el diccionario.

*Se requiere*

* Tener en common-services un lugar centralizado (servidor http) donde hostear los archivos jasper para generar los reportes en los servicios de `customer-services`

**Comment by yamelsenih** [comment]
> Se requiere implementar servicio para hostear internamente los reportes Jaspers.
> 
> Actualmente estos reportes estaban hosteados en la db en el proceso con `attachment:`. Eso con S3 actualmente no tiene soporte así que los reportes no se están generando. @yamelsenih comenta que una posible solución es tener un servicio de hosting interno donde se puedan referenciar estos jasper desde el diccionario.
> 
> _Se requiere_
> 
> * Tener en common-services un lugar centralizado (servidor http) donde hostear los archivos jasper para generar los reportes en los servicios de `customer-services`

Hola @rcapecce entiendo que esto pudiera ser una mejora, sin embargo, sería algo distinto a lo que está aquí

**Comment by yamelsenih** [comment]
**Datos**
- Descripción: **Febrero 2023 DEMO**
- `C_DunningRun_ID=1000198`

**Comment by yamelsenih** [comment]
**Datos**
- Descripción: **Febrero 2023 DEMO**
- `C_DunningRun_ID=1000198`
- Entrada -> Socio de Negocio: **Joaquin Denis** 


Hice el cambio en la configuración del cliente local pero ahora el error es otro con el tipo de letra:
![System_Error](https://github.com/user-attachments/assets/9055a7a8-435a-445b-9a21-b4bef3aee512)

```Log
===========> ProcessUtil.startJavaProcess: org.compiere.jr.report.ReportStarter [37]
net.sf.jasperreports.engine.util.JRFontNotFoundException: Font "Arial" is not available to the JVM. See the Javadoc for more details.
	at net.sf.jasperreports.engine.fonts.FontUtil.checkAwtFont(FontUtil.java:603)
	at net.sf.jasperreports.engine.fill.SimpleTextLineWrapper.loadFont(SimpleTextLineWrapper.java:384)
	at net.sf.jasperreports.engine.fill.SimpleTextLineWrapper.getGeneralFontInfo(SimpleTextLineWrapper.java:354)
	at net.sf.jasperreports.engine.fill.SimpleTextLineWrapper.createFontInfo(SimpleTextLineWrapper.java:294)
	at net.sf.jasperreports.engine.fill.SimpleTextLineWrapper.start(SimpleTextLineWrapper.java:256)
	at net.sf.jasperreports.engine.fill.TextMeasurer.measure(TextMeasurer.java:555)
	at net.sf.jasperreports.engine.fill.JRFillTextElement.chopTextElement(JRFillTextElement.java:654)
	at net.sf.jasperreports.engine.fill.JRFillTextField.prepare(JRFillTextField.java:812)
	at net.sf.jasperreports.engine.fill.JRFillElementContainer.prepareElements(JRFillElementContainer.java:542)
	at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:453)
	at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:428)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillTitle(JRVerticalFiller.java:336)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportStart(JRVerticalFiller.java:267)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:119)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:622)
	at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:414)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:120)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:103)
	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:530)
	at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:954)
	at org.compiere.jr.report.ReportStarter.startProcess(ReportStarter.java:613)
```

**Comment by yamelsenih** [comment]
- Documento: **A6245**
- `C_Invoice_ID=1032696`

Local da error por la fuente `Arial` pero en el servicio sin patches no:

![image](https://github.com/user-attachments/assets/82d898ea-280e-4e4b-98de-cad91d085760)

**Comment by yamelsenih** [comment]
En vue da error por la fuente también, creo que se trata de la construcción sin patches:

https://github.com/user-attachments/assets/083ce26f-0e83-4feb-90ae-124f10e3f122

**Comment by yamelsenih** [comment]
En la instancia con patches da el mismo error
![image](https://github.com/user-attachments/assets/230a6b55-3de4-488f-837b-c55eb026d085)

**Comment by yamelsenih** [comment]
Accabo de hacer un cambio en el reporte para el tipo de letra `Arial` y dejé un fuente por defecto `SansSerif` para validar simplemente y funciona perfecto en vue.

https://github.com/user-attachments/assets/45f31d25-dd45-420e-a85a-26d338dee022

La prueba se puede hacer con los siguientes datos

- Descripción: **Febrero 2023 DEMO**
- `C_DunningRun_ID=1000198`
- Puerto: `24810`
- Entrada -> Socio de Negocio: **Joaquin Denis** 

Se puede revisar desde ya


## Resumen
Los reportes de Jasper están funcionando bien en  vue, las razones por las que no salen y su solución a continuación:

- Mala configuración del gestor de archivos para **System**: Esto se corrige con quitar la referencia a **S3** en la información de la compañía (Como **System**).
![System_Error](https://github.com/user-attachments/assets/31560328-abc9-48b6-9381-b817bb0713bd)
- Fuente no instalada en la imagen de backend: la fuente `Arial` no viene por defecto en las imágenes de linux y hay que instalarla, tanto en la imagen sin patches como en la imagen con patches no está instalada. Recomiendo que se use una fuente que especial únicamente si no hay manera de solucionarlo con una fuente predeterminada para evitar esto.

**Comment by EdwinBetanc0urt** [comment]
Anteriormente se habia agregado `Arial` aca en este cambio https://github.com/solop-develop/adempiere-grpc-server/pull/642 por un tema similar https://github.com/solop-develop/frontend-core/issues/1091

**Comment by yamelsenih** [comment]
> Anteriormente se habia agregado `Arial` aca en este cambio [solop-develop/adempiere-grpc-server#642](https://github.com/solop-develop/adempiere-grpc-server/pull/642) por un tema similar #1091

No recomiendo agregarlo en este proyecto ya que complica más el resto, prefiero que se cambie en los reportes o se haga en otro lado

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/7fa510e9-bf11-454f-b59d-d9cb8e46fac8
