### ISSUE TITLE
[Bug Report] Establecer Producto en línea de Orden de Compra genera error en callout

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#2438]
#### Steps to reproduce

1. Abrir la ventana `Orden de Compra`.
2. Ir a la pestaña `Línea Orden de Compra`.
3. Cambiar a mono registro.
4. Pulsar el botón de `Nuevo`.
5. Establecer algún `Producto`.

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/1d9a7404-b8af-48f4-b1fe-c85564e8ae38

#### Expected behavior
Se espera que en el resultado no se genere error alguno, sin embargo el punto donde lanza un `Null Pointer Exception`, es donde trata de buscar y establecer la versión de la lista de precios.

![imagen](https://github.com/user-attachments/assets/a4b8c179-2293-4067-b8d9-4014494f83e8)

#### Additional context
La traza del log

```log
===========> CalloutOrder.start: start: product [29]
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.sql.Timestamp (java.lang.String is in module java.base of loader 'bootstrap'; java.sql.Timestamp is in module java.sql of loader 'platform')
        at org.compiere.model.CalloutOrder.product(CalloutOrder.java:750)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.compiere.model.CalloutEngine.start(CalloutEngine.java:109)
        at org.spin.grpc.service.UserInterface.processCallout(UserInterface.java:2801)
        at org.spin.grpc.service.UserInterface.lambda$23(UserInterface.java:2675)
        at org.compiere.util.Trx.run(Trx.java:529)
        at org.compiere.util.Trx.run(Trx.java:497)
        at org.spin.grpc.service.UserInterface.runcallout(UserInterface.java:2590)
        at org.spin.grpc.service.UserInterface.runCallout(UserInterface.java:2561)
        at org.spin.backend.grpc.user_interface.UserInterfaceGrpc$MethodHandlers.invoke(UserInterfaceGrpc.java:2086)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:356)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

===========> UserInterface.processCallout: class java.lang.String cannot be cast to class java.sql.Timestamp (java.lang.String is in module java.base of loader 'bootstrap'; java.sql.Timestamp is in module java.sql of loader 'platform') [29]
```

**Comment by Ricargame** [comment]
Cambios disponibles apartir de la versión: https://github.com/solop-develop/frontend-core/releases/tag/4.2.0

https://github.com/user-attachments/assets/332a99fb-fb80-404c-929c-825f2eb83afa
