### ISSUE TITLE
[Bug Report] Error al cargar lineas de orden de compra.

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [solop-develop/vue-1.0#2683]
#### Steps to reproduce

1. Abrir la ventana de ordenes de compra.
2. Ir a la pestaña `Línea Orden de Compra`.
3. Cargar registros.

#### Screenshot or Gif（截图或动态图）

![imagen](https://github.com/user-attachments/assets/ee3697f5-ec1c-4ada-8a2e-2afcb87d7d41)

![imagen](https://github.com/user-attachments/assets/91336a86-c171-43b2-b83b-4dd9180ec0ba)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

#### Additional context
Error del log 
```
===========> RecordUtil.convertListEntitiesResult: null [29]
java.lang.NullPointerException
        at java.base/java.math.BigDecimal.compareTo(BigDecimal.java:3079)
        at org.spin.base.interim.ContextTemporaryWorkaround.setContextAsUnknowColumn(ContextTemporaryWorkaround.java:284)
        at org.spin.base.util.RecordUtil.convertListEntitiesResult(RecordUtil.java:693)
        at org.spin.grpc.service.UserInterface.listTabEntities(UserInterface.java:845)
        at org.spin.grpc.service.UserInterface.listTabEntities(UserInterface.java:713)
        at org.spin.backend.grpc.user_interface.UserInterfaceGrpc$MethodHandlers.invoke(UserInterfaceGrpc.java:1708)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:356)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Ricargame** [comment]
Cambios disponibles a partir de la versión del front: https://github.com/solop-develop/frontend-core/releases/tag/4.4.017

https://github.com/user-attachments/assets/9fa24212-7277-4e10-8b2e-71f337f6fb13
