### ISSUE TITLE
Reporte de Saldos Pendientes no muestra info

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/vue-1.0#2754]
## Bug report

Con filtros default (solo fecha de hoy y transaccion venta SI, no trae nada en VUE y en zk si trae info (se probaron otros filtros pero vue no trae nada)
Detectado en Instancia 24816
Esto ocurre también en 24810 (en zk trae info ok solo con filtro transacción venta SI y Org Agencia SA, pero en vue no trae nada)

Como dato adicional en zk el dato fecha era único "a fecha" (estado de situación a una fecha determinada) pero en vue veo que es un desde/hasta lo que puede modificar el funcionamiento del reporte (fecha inicio/fecha fin)

#### Steps to reproduce

1. [Ingresar en saldos pendientes]
2. [seleccionar parámetros y ejecutar]

#### Screenshot or Gif（截图或动态图）

Ejemplo en 24810

https://github.com/user-attachments/assets/49bdcbf1-23c5-4271-babc-c65b2aca6b5a

Sale OK en ZK

https://github.com/user-attachments/assets/01552537-f261-4b82-8c44-9eafe2fca127

#### Expected behavior

Que el reporte sea consistente en datos respecto a lo que se visualiza en zk (con mismos filtros)

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

 Solop
 Nombre de Implementación:

 ${ADEMPIERE_VERSION} 20240912-1419
 Fecha Versión:

 miércoles, 02 de octubre de 2024, 12:00:00 a. m.
 Número de versión:

 3.9.4
 Versión del Back-End:

 3.8.005-r-17.10-v-1
 Versión del Dictionary RS:

 1.4.9
 Versión del Motor de Reporte:

 1.0.0-dev
 Versión del S3 Gateway RS:

 1.2.7
 Versión del Front-End:

 4.4.017

**Comment by yamelsenih** [comment]
![image](https://github.com/user-attachments/assets/3a1f650b-8c8e-4300-975b-91bf6540d65d)

Con el nuevo motor de reportes hice ciertos cambios en el criterio y uno de ellos es que la agrupación debe ser iniciando por el primer campo y el orden debe ser igual
![image](https://github.com/user-attachments/assets/f89c2c35-b99f-4b88-ac21-32e6866ee29f)

En otras palabras para que funcione bajo la funcionalidad nueva los campos que están marcados como ordenados deben estar agrupados y deben estar de primero, de otra forma no hay manera de hacer una estructura de tipo arbol y la funcionalidad que tenemos como desplegable con hijos.
![image](https://github.com/user-attachments/assets/9fd2b739-f59b-43db-a509-58f98f3604c0)


Por otra parte un campo que esté marcado como ordenado / agrupado no debe contener alguna función de agregado como suma, promedio entre otras

**Comment by EdwinBetanc0urt** [comment]
Esto no se ha podido probar en la instancia dev (http://spdev02.solopapp.com:24814) o en la instancia dev custom (http://spdev02.solopapp.com:24810) ya que pide una clase customizada `org.openup.core.process.RCtaCteOpenAmt` en el report engine, y este no tiene parches o tiene un fork con los paquetes de spuy/openup.

Aca la traza en el backend de report-engine:
```log
2024-10-23T17:15:34.409037242Z -----------> ProcessUtil.startJavaProcess: org.openup.core.process.RCtaCteOpenAmt [45]
2024-10-23T17:15:34.409089922Z java.lang.ClassNotFoundException: org.openup.core.process.RCtaCteOpenAmt
2024-10-23T17:15:34.409096034Z 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
2024-10-23T17:15:34.409100332Z 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
2024-10-23T17:15:34.409104440Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
2024-10-23T17:15:34.409108438Z 	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:141)
2024-10-23T17:15:34.409112465Z 	at org.spin.report_engine.service.ReportProcessor.startProcess(ReportProcessor.java:212)
2024-10-23T17:15:34.409116463Z 	at org.spin.report_engine.service.ReportProcessor.run(ReportProcessor.java:130)
2024-10-23T17:15:34.409120350Z 	at org.spin.report_engine.service.ReportBuilder.lambda$run$5(ReportBuilder.java:253)
2024-10-23T17:15:34.409124408Z 	at org.compiere.util.Trx.run(Trx.java:529)
2024-10-23T17:15:34.409148113Z 	at org.compiere.util.Trx.run(Trx.java:497)
2024-10-23T17:15:34.409152191Z 	at org.spin.report_engine.service.ReportBuilder.run(ReportBuilder.java:251)
2024-10-23T17:15:34.409156188Z 	at org.spin.report_engine.service.Service.getReport(Service.java:191)
2024-10-23T17:15:34.409160075Z 	at org.spin.report_engine.controller.ReportService.getReport(ReportService.java:55)
2024-10-23T17:15:34.409164023Z 	at org.spin.backend.grpc.report_engine.ReportEngineGrpc$MethodHandlers.invoke(ReportEngineGrpc.java:446)
2024-10-23T17:15:34.409168000Z 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
2024-10-23T17:15:34.409172048Z 	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
2024-10-23T17:15:34.409176015Z 	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
2024-10-23T17:15:34.409179994Z 	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
2024-10-23T17:15:34.409184192Z 	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
2024-10-23T17:15:34.409188149Z 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:356)
2024-10-23T17:15:34.409192157Z 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
2024-10-23T17:15:34.409196234Z 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
```
